# Generated by Django 4.0 on 2022-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('cards', '0002_carditem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='store.Variation'),
        ),
    ]
