# Generated by Django 4.0 on 2022-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('cards', '0007_rename_variations_carditem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carditem',
            name='variation',
        ),
        migrations.AddField(
            model_name='carditem',
            name='variations',
            field=models.ManyToManyField(to='store.Variation'),
        ),
    ]
