# Generated by Django 4.0 on 2022-04-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cards', '0008_remove_carditem_variation_carditem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
    ]
